Feature/cron notification update
UKHomeOffice/coa pull request #74
Opened 2024-07-31 19:13 UTC by adityababumallisettiHO

## What? 
## Why? 
## How? 
## Testing?
## Screenshots (optional)
## Anything Else? (optional)
## Check list

- [ ] I have reviewed my own pull request
- [ ] I have written tests (if relevant)

2024-08-05 16:46 UTC, sulthan-ahmed commented
So this is going to post to slack whenever we have a vulnerability even if it is low?

2024-08-05 17:45 UTC, dk4g requested changes

2024-08-05 20:15 UTC, adityababumallisettiHO commented on .drone.yml
> +      SERVICE_URL: https://acp-trivy.acp-trivy.svc.cluster.local:443
@dk4g SERVICE_URL has been removed which has been added to test the impact on the scan

2024-08-05 20:16 UTC, adityababumallisettiHO commented on .drone.yml
>          IMAGE_NAME: node:20.15.0-alpine3.20@sha256:24c14a8a192a6e81d0942929a344f7a4bdf0db8e3b3c77d64a5eb8a4b0c759b7
Thanks @dk4g , Now after rearranging order we have scan os cron step running before scanning node packages.

2024-08-05 20:19 UTC, adityababumallisettiHO commented on .drone.yml
>          IMAGE_NAME: coa:${DRONE_COMMIT_SHA}
@dk4g , This was a good suggestion. Now we can ensure all the cronsteps are running without blocking each other. I have applied these changes to the code

2024-08-07 13:18 UTC, dk4g approved these changes

2024-08-08 09:37 UTC, gadorcruz approved these changes
LGTM

2024-08-08 12:31 UTC, merged

2024-08-08 15:37 UTC, sulthan-ahmed commented
Does/can the notification say if it is a critical/high or whatever rating the vulnerability is? Obviously if it is critical, it would be good to be alerted to be highlighted

2024-08-08 15:42 UTC, dk4g commented
> Does/can the notification say if it is a critical/high or whatever rating the vulnerability is? Obviously if it is critical, it would be good to be alerted to be highlighted

There is no visibility of the scan reports in the slack message, these notifications are an indication that not all steps have been successfully resolved.

2024-08-16 10:17 UTC, sulthan-ahmed commented
fair enough, out of scope for this PR
I just wonder if we can send the information as part of the pay load to slack and then present that in the slack message.  It's just a thought.